// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy78DTvdvEAuxHqtiayu7Ih515571Ne_g',
    appId: '1:662752158223:web:fb00fa4e1e1cd9dee2797a',
    messagingSenderId: '662752158223',
    projectId: 'rental-app123',
    authDomain: 'rental-app123.firebaseapp.com',
    storageBucket: 'rental-app123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmdolsBRRdCk0jRZ9kEQnuBlWpEhZ0cuw',
    appId: '1:662752158223:android:29152b2591bea3b5e2797a',
    messagingSenderId: '662752158223',
    projectId: 'rental-app123',
    storageBucket: 'rental-app123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkrrB5kYXTuYvWMP6QsnqBGPSIx4ifwB4',
    appId: '1:662752158223:ios:7a8a48ae52687705e2797a',
    messagingSenderId: '662752158223',
    projectId: 'rental-app123',
    storageBucket: 'rental-app123.firebasestorage.app',
    iosBundleId: 'com.example.rentalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkrrB5kYXTuYvWMP6QsnqBGPSIx4ifwB4',
    appId: '1:662752158223:ios:7a8a48ae52687705e2797a',
    messagingSenderId: '662752158223',
    projectId: 'rental-app123',
    storageBucket: 'rental-app123.firebasestorage.app',
    iosBundleId: 'com.example.rentalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy78DTvdvEAuxHqtiayu7Ih515571Ne_g',
    appId: '1:662752158223:web:fbd88a81fa0f30a8e2797a',
    messagingSenderId: '662752158223',
    projectId: 'rental-app123',
    authDomain: 'rental-app123.firebaseapp.com',
    storageBucket: 'rental-app123.firebasestorage.app',
  );

}